# Generated by Django 3.2 on 2021-11-23 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erkrord', '0004_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
