# Generated by Django 3.2 on 2021-11-24 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erkrord', '0008_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
