# Generated by Django 3.2 on 2021-11-27 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erkrord', '0014_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
