# Generated by Django 3.2 on 2021-11-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erkrord', '0019_auto_20211129_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
