# Generated by Django 3.2 on 2021-11-29 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erkrord', '0020_post_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='views',
        ),
    ]
